spring:
  config:
    import: file:.env[.properties]
  jpa:
    properties:
      hibernate:
        format_sql: false
        show_sql: false
        dialect: org.hibernate.dialect.MySQL8Dialect
#        cache:
#          use_second_level_cache: false
#          use_query_cache: false;
    hibernate:
      ddl-auto: create # 이 부분 설정 주의 필요
  datasource:
    url: ${DOCKER_MYSQL_URL}
    username: ${DOCKER_MYSQL_USERNAME}
    password: ${DOCKER_MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
